# Generated by Django 2.2 on 2020-03-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtvshowApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='VeryOldTVsshows'),
            preserve_default=False,
        ),
    ]
