# Generated by Django 2.2 on 2020-03-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtvshowApp', '0002_show_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Network',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='Title',
            field=models.CharField(max_length=255),
        ),
    ]
